import { failureModeScanner } from './failureMode'
import { securityProbe } from './securityProbe'
import { hallucinationDetector } from './hallucinationDetector'
import { propertyGenerator } from './propertyGenerator'
import { complexityProfiler } from './complexityProfiler'
import { differentialRunner } from './differentialRunner'
import { oracleChecker } from './oracleChecker'
import { mutationScorer } from './mutationScorer'
import { promptTestabilityScore } from './promptTestability'
import { aiReviewAssistant } from './aiReviewAssistant'

const MODULE_REGISTRY = {
  failureMode: failureModeScanner,
  security: securityProbe,
  hallucination: hallucinationDetector,
  property: propertyGenerator,
  complexity: complexityProfiler,
  differential: differentialRunner,
  oracle: oracleChecker,
  mutation: mutationScorer,
  prompt: promptTestabilityScore,
  aiReview: aiReviewAssistant,
}

export const runAnalysis = async (code, language, selectedModules, prompt = '', apiKey = '') => {
  const findings = []

  for (const moduleName of selectedModules) {
    const moduleFunc = MODULE_REGISTRY[moduleName]
    if (moduleFunc) {
      try {
        let moduleFindings
        if (moduleName === 'prompt') {
          moduleFindings = moduleFunc(code, prompt)
        } else if (moduleName === 'aiReview') {
          moduleFindings = await moduleFunc(code, language, apiKey)
        } else {
          moduleFindings = moduleFunc(code, language)
        }
        findings.push(...moduleFindings)
      } catch (error) {
        console.error(`Error in module ${moduleName}:`, error)
      }
    }
  }

  return findings.sort((a, b) => {
    const severityOrder = { Critical: 0, High: 1, Medium: 2, Info: 3 }
    return severityOrder[a.severity] - severityOrder[b.severity]
  })
}

export const getModuleInfo = (moduleName) => {
  const info = {
    failureMode: {
      name: 'Failure Mode Scanner',
      icon: '🔍',
      description: 'Detects AI-characteristic bugs: off-by-one errors, silent exceptions, unbounded loops, type coercion, magic numbers, and implicit globals.',
      estimatedTime: '~5s',
    },
    security: {
      name: 'Security Probe',
      icon: '🔒',
      description: 'Scans for OWASP Top 10 vulnerabilities: SQL injection, XSS, hardcoded credentials, weak crypto, path traversal, and disabled security controls.',
      estimatedTime: '~5s',
    },
    hallucination: {
      name: 'Hallucination Detector',
      icon: '👻',
      description: 'Cross-references method calls against known APIs to detect non-existent or hallucinated function calls generated by AI.',
      estimatedTime: '~5s',
    },
    property: {
      name: 'Property Generator',
      icon: '🎯',
      description: 'Analyzes function signatures for testability: detects pure functions, high parameter counts, and suggests property-based test strategies.',
      estimatedTime: '~3s',
    },
    complexity: {
      name: 'Complexity Profiler',
      icon: '📊',
      description: 'Identifies performance risks: nested loops, sync blocking, excessive DOM manipulation, string concatenation in loops, and memory leaks.',
      estimatedTime: '~5s',
    },
    differential: {
      name: 'Differential Runner',
      icon: '⚖️',
      description: 'Identifies differential testing candidates: versioned functions, algorithm re-implementations, data transformations, and regex patterns.',
      estimatedTime: '~3s',
    },
    oracle: {
      name: 'Oracle Checker',
      icon: '📋',
      description: 'Validates code contracts: missing input validation, inconsistent return types, unvalidated API responses, and missing error contracts.',
      estimatedTime: '~5s',
    },
    mutation: {
      name: 'Mutation Scorer',
      icon: '🧬',
      description: 'Scores mutation testing susceptibility: boundary operators, boolean negation targets, return value mutations, and conditional branches.',
      estimatedTime: '~5s',
    },
    prompt: {
      name: 'Prompt Testability',
      icon: '📝',
      description: 'Evaluates AI prompt quality for testability: checks for edge cases, constraints, error semantics, dependency injection, and pure functions.',
      estimatedTime: '~2s',
    },
    aiReview: {
      name: 'AI Review Assistant',
      icon: '🤖',
      description: 'Claude-powered code review targeting AI anti-patterns: omniscient functions, cargo-cult patterns, leaky abstractions, and naming issues.',
      estimatedTime: '~15s',
    },
  }
  return info[moduleName]
}
