/**
 * Analysis Comparison Diff Exporter
 *
 * Generates markdown diff reports comparing two analysis runs,
 * showing new, resolved, and persistent findings.
 */

export function compareAnalyses(before, after) {
  const beforeKeys = new Set(before.map(f => `${f.module}::${f.category}`))
  const afterKeys = new Set(after.map(f => `${f.module}::${f.category}`))

  const newFindings = after.filter(f => !beforeKeys.has(`${f.module}::${f.category}`))
  const resolvedFindings = before.filter(f => !afterKeys.has(`${f.module}::${f.category}`))
  const persistent = after.filter(f => beforeKeys.has(`${f.module}::${f.category}`))

  const beforeScore = computeScore(before)
  const afterScore = computeScore(after)
  const delta = afterScore - beforeScore

  return {
    newFindings,
    resolvedFindings,
    persistent,
    beforeCount: before.length,
    afterCount: after.length,
    beforeScore,
    afterScore,
    delta,
    improved: delta > 0,
  }
}

function computeScore(findings) {
  const actionable = findings.filter(f => f.severity !== 'Info')
  if (actionable.length === 0) return 100
  const critical = actionable.filter(f => f.severity === 'Critical').length
  const high = actionable.filter(f => f.severity === 'High').length
  const medium = actionable.filter(f => f.severity === 'Medium').length
  const weighted = (critical * 10) + (high * 5) + (medium * 2)
  const avgPenalty = weighted / actionable.length
  return Math.min(100, Math.max(0, Math.round(100 - avgPenalty * 10)))
}

export function exportDiffMarkdown(comparison, metadata = {}) {
  const { newFindings, resolvedFindings, persistent, beforeCount, afterCount, beforeScore, afterScore, delta } = comparison
  const arrow = delta > 0 ? '\u2191' : delta < 0 ? '\u2193' : '\u2192'
  const ts = metadata.timestamp || new Date().toISOString()

  const lines = [
    '# Analysis Comparison Report',
    '',
    `**Date:** ${new Date(ts).toLocaleString()}`,
    `**Language:** ${metadata.language || 'N/A'}`,
    '',
    '## Score Summary',
    '',
    `| Metric | Before | After | Change |`,
    `|--------|--------|-------|--------|`,
    `| Score | ${beforeScore}% | ${afterScore}% | ${delta > 0 ? '+' : ''}${delta}% ${arrow} |`,
    `| Findings | ${beforeCount} | ${afterCount} | ${afterCount - beforeCount > 0 ? '+' : ''}${afterCount - beforeCount} |`,
    '',
  ]

  if (resolvedFindings.length > 0) {
    lines.push(`## Resolved (${resolvedFindings.length})`, '')
    resolvedFindings.forEach(f => {
      lines.push(`- ~~**${f.category}**~~ (${f.severity}) \u2014 ${f.moduleName || f.module}`)
    })
    lines.push('')
  }

  if (newFindings.length > 0) {
    lines.push(`## New Issues (${newFindings.length})`, '')
    newFindings.forEach(f => {
      lines.push(`- **${f.category}** (${f.severity}) \u2014 ${f.moduleName || f.module}`)
      if (f.description) lines.push(`  > ${f.description}`)
    })
    lines.push('')
  }

  if (persistent.length > 0) {
    lines.push(`## Persistent (${persistent.length})`, '')
    persistent.forEach(f => {
      lines.push(`- **${f.category}** (${f.severity}) \u2014 ${f.moduleName || f.module}`)
    })
    lines.push('')
  }

  lines.push('---')
  lines.push(`*Generated by ValidAI v${metadata.version || '1.1.0'}*`)

  return lines.join('\n')
}

export function downloadDiffReport(content, filename) {
  const blob = new Blob([content], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename || `validai-diff-${Date.now()}.md`
  a.click()
  URL.revokeObjectURL(url)
}
