export const generateGitHubComment = (findings, metadata) => {
  let comment = `## ValidAI Code Review\n\n`
  
  const critical = findings.filter(f => f.severity === 'Critical').length
  const high = findings.filter(f => f.severity === 'High').length
  const medium = findings.filter(f => f.severity === 'Medium').length
  
  comment += `### Summary\n`
  comment += `- **Critical Issues:** ${critical}\n`
  comment += `- **High Issues:** ${high}\n`
  comment += `- **Medium Issues:** ${medium}\n`
  comment += `- **Total Findings:** ${findings.length}\n\n`
  
  if (findings.length === 0) {
    comment += `✅ No issues found!\n`
    return comment
  }
  
  comment += `### Critical Issues\n`
  findings.filter(f => f.severity === 'Critical').forEach((f, idx) => {
    comment += `${idx + 1}. **${f.category}** (Line ${f.lineNumber})\n`
    comment += `   ${f.description}\n`
    comment += `   > ${f.suggestion}\n\n`
  })
  
  comment += `### High Priority Issues\n`
  findings.filter(f => f.severity === 'High').forEach((f, idx) => {
    comment += `${idx + 1}. **${f.category}** (Line ${f.lineNumber})\n`
    comment += `   ${f.description}\n\n`
  })
  
  comment += `---\n`
  comment += `*Generated by [ValidAI](https://github.com/jj-shen99/valid_ai) — Testing Framework for AI-Generated Code*\n`
  
  return comment
}

export const createGitHubIssue = async (token, owner, repo, findings, metadata) => {
  const title = `ValidAI: ${findings.filter(f => f.severity === 'Critical').length} critical issues found`
  const body = generateGitHubComment(findings, metadata)
  
  try {
    const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
      method: 'POST',
      headers: {
        'Authorization': `token ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        title,
        body,
        labels: ['validai', 'code-review'],
      }),
    })
    
    if (!response.ok) {
      throw new Error(`GitHub API error: ${response.statusText}`)
    }
    
    return await response.json()
  } catch (error) {
    console.error('Failed to create GitHub issue:', error)
    throw error
  }
}

export const postPullRequestComment = async (token, owner, repo, prNumber, findings, metadata) => {
  const body = generateGitHubComment(findings, metadata)
  
  try {
    const response = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/issues/${prNumber}/comments`,
      {
        method: 'POST',
        headers: {
          'Authorization': `token ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ body }),
      }
    )
    
    if (!response.ok) {
      throw new Error(`GitHub API error: ${response.statusText}`)
    }
    
    return await response.json()
  } catch (error) {
    console.error('Failed to post PR comment:', error)
    throw error
  }
}
