/**
 * GitHub Issue Exporter
 *
 * Creates GitHub issues from analysis findings.
 * Supports single-finding and batch export.
 */

const SEVERITY_LABELS = {
  Critical: 'priority: critical',
  High: 'priority: high',
  Medium: 'priority: medium',
  Info: 'priority: low',
}

export function formatIssueTitle(finding) {
  return `[ValidAI] ${finding.severity}: ${finding.category}`
}

export function formatIssueBody(finding, metadata = {}) {
  const lines = [
    `## ${finding.category}`,
    '',
    `**Severity:** ${finding.severity}`,
    `**Module:** ${finding.moduleName || finding.module}`,
    finding.lineNumber ? `**Line:** ${finding.lineNumber}` : '',
    '',
    '### Description',
    finding.description,
    '',
    '### Suggestion',
    finding.suggestion,
  ]

  if (finding.codeSnippet) {
    lines.push('', '### Code Snippet', '```', finding.codeSnippet, '```')
  }

  if (finding.autoFix) {
    lines.push('', '### Auto-Fix', '```diff', `- ${finding.autoFix.replace}`, `+ ${finding.autoFix.with}`, '```')
  }

  lines.push('', '---', `*Generated by ValidAI v${metadata.version || '0.9.0'} on ${new Date().toISOString()}*`)

  return lines.filter(l => l !== undefined).join('\n')
}

export function getIssueLabels(finding) {
  const labels = ['validai']
  if (SEVERITY_LABELS[finding.severity]) {
    labels.push(SEVERITY_LABELS[finding.severity])
  }
  if (finding.module) {
    labels.push(`module: ${finding.module}`)
  }
  return labels
}

export async function createGitHubIssue(finding, { owner, repo, token, metadata = {} }) {
  if (!owner || !repo || !token) {
    throw new Error('Missing required GitHub parameters: owner, repo, token')
  }

  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
    method: 'POST',
    headers: {
      'Authorization': `token ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      title: formatIssueTitle(finding),
      body: formatIssueBody(finding, metadata),
      labels: getIssueLabels(finding),
    }),
  })

  if (!response.ok) {
    const err = await response.json().catch(() => ({}))
    throw new Error(`GitHub API error ${response.status}: ${err.message || 'Unknown error'}`)
  }

  return response.json()
}

export async function createBatchIssues(findings, options) {
  const results = []
  for (const finding of findings) {
    try {
      const issue = await createGitHubIssue(finding, options)
      results.push({ finding, issue, success: true })
    } catch (error) {
      results.push({ finding, error: error.message, success: false })
    }
  }
  return results
}

// Build a GitHub issue URL for manual creation (no API needed)
export function buildIssueUrl(finding, { owner, repo }) {
  const title = encodeURIComponent(formatIssueTitle(finding))
  const body = encodeURIComponent(formatIssueBody(finding))
  const labels = encodeURIComponent(getIssueLabels(finding).join(','))
  return `https://github.com/${owner}/${repo}/issues/new?title=${title}&body=${body}&labels=${labels}`
}
