/**
 * Analysis Summary Report Generator
 *
 * Auto-generates a markdown summary report from analysis results,
 * including severity breakdown, module stats, top issues, and recommendations.
 */

export function generateSummaryReport(findings, metadata = {}) {
  const timestamp = metadata.timestamp || new Date().toISOString()
  const language = metadata.language || 'unknown'
  const modules = metadata.modules || []
  const score = metadata.score ?? 0

  const byModule = {}
  const bySeverity = { Critical: 0, High: 0, Medium: 0, Info: 0 }

  findings.forEach(f => {
    bySeverity[f.severity] = (bySeverity[f.severity] || 0) + 1
    if (!byModule[f.moduleName || f.module]) byModule[f.moduleName || f.module] = 0
    byModule[f.moduleName || f.module]++
  })

  const actionable = findings.filter(f => f.severity !== 'Info')
  const topIssues = actionable.slice(0, 5)

  const lines = [
    `# ValidAI Analysis Report`,
    '',
    `**Date:** ${new Date(timestamp).toLocaleString()}`,
    `**Language:** ${language}`,
    `**Modules:** ${modules.length} active`,
    `**Quality Score:** ${score}%`,
    '',
    '---',
    '',
    '## Summary',
    '',
    `| Severity | Count |`,
    `|----------|-------|`,
    `| Critical | ${bySeverity.Critical} |`,
    `| High | ${bySeverity.High} |`,
    `| Medium | ${bySeverity.Medium} |`,
    `| Info | ${bySeverity.Info} |`,
    `| **Total** | **${findings.length}** |`,
    '',
  ]

  if (Object.keys(byModule).length > 0) {
    lines.push('## Findings by Module', '')
    lines.push('| Module | Count |')
    lines.push('|--------|-------|')
    Object.entries(byModule)
      .sort((a, b) => b[1] - a[1])
      .forEach(([mod, count]) => {
        lines.push(`| ${mod} | ${count} |`)
      })
    lines.push('')
  }

  if (topIssues.length > 0) {
    lines.push('## Top Issues', '')
    topIssues.forEach((f, i) => {
      lines.push(`### ${i + 1}. ${f.category}`)
      lines.push('')
      lines.push(`- **Severity:** ${f.severity}`)
      lines.push(`- **Module:** ${f.moduleName || f.module}`)
      if (f.lineNumber) lines.push(`- **Line:** ${f.lineNumber}`)
      lines.push(`- **Description:** ${f.description}`)
      lines.push(`- **Suggestion:** ${f.suggestion}`)
      lines.push('')
    })
  }

  // Recommendations
  lines.push('## Recommendations', '')
  if (bySeverity.Critical > 0) {
    lines.push(`- \u26a0\ufe0f **${bySeverity.Critical} critical issues** require immediate attention.`)
  }
  if (bySeverity.High > 0) {
    lines.push(`- \ud83d\udfe0 **${bySeverity.High} high-severity issues** should be addressed before deployment.`)
  }
  if (score >= 80) {
    lines.push('- \u2705 Code quality is good. Focus on remaining issues for an excellent score.')
  } else if (score >= 50) {
    lines.push('- \u26a0\ufe0f Code quality needs improvement. Address critical and high findings first.')
  } else {
    lines.push('- \ud83d\udea8 Code quality is poor. Significant refactoring is recommended.')
  }
  lines.push('')
  lines.push('---')
  lines.push(`*Generated by ValidAI v${metadata.version || '1.0.0'}*`)

  return lines.join('\n')
}

export function downloadReport(content, filename) {
  const blob = new Blob([content], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename || `validai-report-${Date.now()}.md`
  a.click()
  URL.revokeObjectURL(url)
}
